# Sctipted by:
#   Po-temkin
#
# Tested on:
#   Ansible: 2.9
#   Splunk Enterprise for Windows:
#     Version: 9.0.0.1
#     Build: 9e907cedecb1
#
#  Name:
#    spl_install_spl.yml
#
#  Description:
#    Installing Splunk Enterprise
#
#  Input:
#    spl_home_dir # Path to Splunk home dir; Default 'C:\Program Files\Splunk'; Taken from inventory
#    spl_install_shortcut # Specify whether or not creating shortcut on desktop and Start Menu
#    spl_installer_name # Name of Splunk installer
#    spl_installer_location # Installer location
#    spl_username # Splunk admin account
#    spl_password # Password of admin account
#      
#  Output:
#    -

---
      
- name: 'SLP :: Copying {{spl_installer_name}} installer'
  win_copy:
  #ansible.windows.win_copy:
    src: '{{ spl_installer_location }}\{{ spl_installer_name }}'
    dest: '{{ ansible_env.TEMP }}\{{ spl_installer_name }}'
    remote_src: yes

- name: 'SPL :: Installing Splunk Enterprise'
  win_package:
  #ansible.windows.win_package:
    path: '{{ ansible_env.TEMP }}\{{ spl_installer_name }}'
    provider: msi
    arguments: 'AGREETOLICENSE=Yes INSTALLDIR={{ spl_home_dir }} INSTALL_SHORTCUT={{ spl_install_shortcut }} SPLUNKUSERNAME={{ spl_username }} SPLUNKPASSWORD={{ spl_password }}'
    log_path: '{{ ansible_env.TEMP }}\{{ spl_installer_name.split(".")[0] }}.log'

- name: 'SPL :: Removing TEMP files'
  win_file:
  #ansible.windows.win_file:
    path: '{{ ansible_env.TEMP }}\{{ spl_installer_name }}'
    state: absent